//
//  MockData.swift
//  Apple-Frameworks
//
//  Created by Sean Allen on 11/2/20.
//

import Foundation

struct Fiszki: Hashable, Identifiable {
    
    var id = UUID()
    let name: String
    let description: String
}

struct MockData {
    static let sampleFramework = Fiszki(name: "ARKit",
                                           description: "ARKit 4 introduces a brand-new Depth API, creating a new way to access the detailed depth information gathered by the LiDAR Scanner on iPhone 12 Pro, iPhone 12 Pro Max, and iPad Pro.\n\nLocation Anchors leverages the higher-resolution data in Apple Maps to place AR experiences at a specific point in the world in your iPhone and iPad apps. And support for face tracking extends to all devices with the Apple Neural Engine and a front-facing camera, so even more users can experience the joy of AR in photos and videos.")
    
    static let frameworks = [
        Fiszki(name: "PYTANIA OGÓLNE",
                  description: "ZAGADNIENIA OGÓLNE"),
               
        Fiszki(name: "Metody oceniania złożoności obliczeniowej algorytmu",
                  description: "Istnieje wiele metod oceniania złożoności algorytmu, które można wykorzystać do określenia, ile czasu i zasobów (takich jak pamięć lub procesor) będzie potrzebne do wykonania danego algorytmu. Oto kilka przykładów takich metod:\n Ocena złożoności w czasie: Ta metoda mierzy, ile operacji musi wykonać algorytm, aby wykonać swoje zadanie. Złożoność w czasie jest często określana w notacji O(n), gdzie n to rozmiar danych wejściowych. Na przykład jeśli algorytm ma złożoność O(n), oznacza to, że ilość operacji wzrasta proporcjonalnie do rozmiaru danych wejściowych.\n Ocena złożoności pamięci: Ta metoda mierzy, ile pamięci jest potrzebne do przechowywania danych i struktur danych potrzebnych do wykonania algorytmu. Złożoność w pamięci jest często określana w notacji O()."),
        
       Fiszki(name: "Trypologia przestępstw komputerowych",
                  description: "Przestępstwa komputerowe to rodzaj przestępstw, które dotyczą komputerów, sieci komputerowych lub systemów informatycznych. Oto kilka przykładów:\n Hacking: to nielegalne włamanie się do komputera lub sieci komputerowej, aby uzyskać dostęp do poufnych informacji lub kontrolować działanie systemu.\n Phishing: to rodzaj oszustwa, w którym cyberprzestępcy wysyłają fałszywe e-maile lub wiadomości tekstowe, wyglądające jak oficjalne komunikaty od banków lub innych instytucji, aby wyłudzić dane osobowe lub finansowe od ofiar.\n Ataki DDoS(Distributed Denial of Service): to rodzaj ataku w którym cyberprzestępcy wysyłają dużą liczbę żądań do serwera lub sieci, aby zablokować dostęp do niego.\n Włamanie do konta: to nielegalne uzyskanie dostępu do czyjegoś konta na serwisie internetowym lub aplikacji bez jego zgody.\n Krętactwo: to nielegalne modyfikowanie lub niszczenie danych komputerowych."),
        
        Fiszki(name: "Programy służące do DTP (Desktop Publishing)",
                  description: "DTP to proces tworzenia dokumentów drukowych lub elektronicznych za pomocą specjalnych narzędzi i oprogramowania. Oto kilka przykładów:\n Adobe InDesign: to profesjonalne narzędzie do tworzenia publikacji cyfrowych i drukowanych, takich jak katalogi, broszury i gazety.\n Adobe Illustrator: program do tworzenia grafiki wektorowej, takiej jak loga, ikony i ilustracje.\n Adobe Photoshop: to narzędzie do edycji zdjęć i obrazów, umożliwiające m. in. retusz, dodawanie efektów i tworzenie grafiki rastowej.\n CorelDRAW: program do tworzenia grafiki wektoroweji rastrowej, a także publikacji drukowanych i cyfrowych.\n QuarlkXPress: to narzędzie do tworzenia publikacji drukowanych i cyfrowych, takich jak gazety, magazyny i katalogi.\n Scribus: darmowy program do tworzenia publikacji drukowanych i elektronicznych, takich jak ulotki, broszury i gazety."),
        
        Fiszki(name: "Leasing (operacyjny, finansowy) jako zewnętrzne formy pozyskiwania kapitału",
                  description: "Leasing to rodzaj umowy, w której leasingodawca ( czyli firma leasingowa) udostępnia leasingobiorcy ( czyli przedsiębiorstwu lub osobie prywatnej) konkretny przedmiot (np. samochód, maszynę sprzęt) a leasingobiorca opłaca comiesięczne raty za jego użytkowanie.\n Leasing może mieć formę operacyjn.a lub finansową.\n W leasingu operacyjnym przedmiot leasingu jest wliczany w koszty uzyskania przychodu przez leasingobiorcę. Leasingodawca jest właścicielem przedmiotu leasingu i ponosi jego koszty, a leasingobiorca opłaca comiesięczne raty za użytkowanie przedmiotu. Po zakończeniu okresu leasingu przedmiot może być odkupiony przez leasingobiorcę po określonej cenie lub zwrócony leasingodawcy.\n W leasingu finansowym przedmiot leasingu jest wliczony w bilans leasingobiorcy jako jego własność. Leasingobiorca opłaca comiesięczne raty, ale po zakończeniu okresu leasingu automatycznie staje się właścicielem przedmiotu. Leasing jest często wykorzystywany jako zewnętrzna forma pozyskiwania kapitału przez przedsiębiorstwa, ponieważ umo∑liwia im uzyksanie potrzebnych im środków bez konieczności ich kupowania lub pożyczania. Leasing może być również atrakcyjnym rozwiązaniem dla osób prywatnych, ponieważ umożliwia im korzystanie z przedmiotu leasingu bez konieczności jego natychmiastowego zakupu.\n Na przykład, przedsiębiorstwo X potrzebuje nowego samochodu dostawczego, aby rozwijać swoją działalność. Zamiast kupować samochód za gotówkę lub pożyczać pieniądze od banku, przedsiębiorstwo X może wziąć w leasing samochód od leasingodawcy. Przedsiębiorstwo X będzie płacić leasingodawcy określoną ratę leasingową przez określony czas, po czym będzie mieć opcję wykupienia samochodu lub zwrócenia go leasingodawcy. W ten sposób przedsiębiorstwo X może pozyskaćpotrzebny samochód bez konieczności ponoszenia dużych kosztów związanych z jego zakupem"),
        
        Fiszki(name: "Klasyczne funkcje trendu jako narzędzie predykcji",
                  description: "Trend to wykrywalna zmiana w danych w czasie. Klasyczne funkcje trendu to narzędzia statystyczne, które pozwalają na określenie kierunku i poziomu zmian w danych w czasie. Przykłady takich funkcji to:\n Prosta linia trendu: polega na dopasowaniu prostej do danych, aby określić kierunek i poziom zmian w danych.\n Regresja liniowa: polega na dopasowaniu funkcji liniowej do danych, aby określić kierunek i poziom zmian w danych oraz przewidywać wartości w przyszłości.\n Regresja wielomianowa: polega na dopasowaniu wielomianu do danych, co pozwala na określenie bardziej skomplikowanych trendów i poziomów zmian w danych.\n SMA (średnia krocząca): polega na obliczeniu średniej dla określonego okresu czasu, co pozwala na określenie kierunku i poziomu zmian w danych.\n Te funkcje trendu są często używane w analizie danych, biznesie, finansach, ekonometrii, itp. pozwalają one na przewidywanie przyszłych zmian i podejmowanie odpowiednich decyzji.\n Jednym z przykładów zastosowania klasycznej funkcji trendu jako narzędzia predykcji jest prognozowanie sprzedaży produktów w sklepie internetowym. W tym celu można wykorzystać funkcję regresji liniowej, która pozwala na dopasowanie funkcji liniowej do danych dotyczących sprzedaży produktów w określonych dniach lub miesiącach. Po dopasowaniu funkcji, można przewidywać sprzedaż produktów w przyszłości.\n Innym przykładem jest prognozowanie cen akcji na giełdzie. Można wykorzystać funkcję SMA (średniej kroczącej) do określenia kierunku i poziomu zmian cen akcji. Po określeniu trendu, można przewidywać przyszłe ceny akcji.\n Jeszcze innym przykładem jest prognozowanie liczby klientów w restauracji. Można wykorzystać funkcję regresji wielomianowej, która pozwala na dopasowanie wielomianu do danych dotyczących liczby klientów w określonych dniach lub godzinach. Po dopasowaniu funkcji, można przewidywać liczbę klientów w przyszłości.\n Te przykłady pokazują jak klasyczne funkcje trendu mogą być skutecznie wykorzystywane do prognozowania różnych zmiennych w różnych dziedzinach."),
        
        Fiszki(name: "Zagadnienie prawa autorskiego.",
                  description: "Prawo autorskie to system prawny, który chroni twórczość literacką, artystyczną i naukową przed nielegalnym kopiowaniem i wykorzystywaniem bez zgody autora. Prawo autorskie obejmuje różnego rodzaju dzieła, takie jak książki, artykuły, filmy, muzykę, zdjęcia itp.\n W większości krajów prawo autorskie przyznaje autorom prawo do decydowania o sposobie wykorzystywania ich dzieł oraz do otrzymywania wynagrodzenia za ich wykorzystanie. Prawo autorskie obejmuje także tzw. prawa pokrewne, które chronią osoby i podmioty, które współtworzą dzieło, takie jak wydawcy, wykonawcy i producenci.\n Istnieją różne sposoby ochrony praw autorskich, takie jak rejestracja dzieła, oznaczanie dzieła symbolem © lub oznaczeniem prawa autorskiego, czy też korzystanie z licencji na korzystanie z dzieła. Prawo autorskie nie jest jednak nieograniczone i istnieją pewne wyjątki, takie jak dozwolony użytek czy cytat, które pozwalają na korzystanie z dzieła bez zgody autora w określonych sytuacjach."),
        
        Fiszki(name: "Cena a popyt i podaż",
                  description: "Cena to kwota, którą trzeba zapłacić za określony towar lub usługę. Popyt to ilość danego towaru lub usługi, jaką konsumenci są gotowi kupić w określonym przedziale czasu przy określonej cenie. Podaż to ilość danego towaru lub usługi, jaką producenci są gotowi sprzedać w określonym przedziale czasu przy określonej cenie.\n Na cenę danego towaru lub usługi wpływają zarówno popyt, jak i podaż. Jeśli popyt jest większy niż podaż, cena rośnie, ponieważ konsumenci są gotowi zapłacić więcej za dany towar lub usługę. Jeśli natomiast podaż jest większa niż popyt, cena spada, ponieważ producenci są zmuszeni obniżyć cenę, aby sprzedać swoje towary lub usługi.\n Inne czynniki, takie jak koszty produkcji, wysokość podatków czy stopa inflacji, również mogą wpływać na cenę danego towaru lub usługi. W ekonomii cena jest uważana za istotny element rynku, ponieważ odgrywa ważną rolę w alokacji zasobów i wpływa na decyzje konsumentów i producentów."),
        
        Fiszki(name: "Podstawowe aplikacje Internetu",
                  description: "Internet to globalna sieć komputerowa, która umożliwia przesyłanie danych pomiędzy komputerami na całym świecie. Podstawowe aplikacje Internetu to narzędzia, które umożliwiają korzystanie z Internetu i jego zasobów. Oto kilka przykładów podstawowych aplikacji Internetu:\n Przeglądarka internetowa to oprogramowanie, które umożliwia przeglądanie stron internetowych i korzystanie z różnych usług online. Przykłady przeglądarek internetowych to m.in. Google Chrome, Mozilla Firefox, Internet Explorer czy Safari.\n Poczta elektroniczna (e-mail) to usługa umożliwiająca wysyłanie i odbieranie wiadomości elektronicznych. Można ją korzystać za pomocą specjalnego oprogramowania lub przez przeglądarkę internetową.\n Usługi społecznościowe to serwisy internetowe, które umożliwiają komunikowanie się i wymianę informacji z innymi osobami poprzez profile użytkowników, grupy dyskusyjne czy wiadomości prywatne."),
        
        Fiszki(name: "Znaczenie UML w procesach tworzenia systemów",
                  description: "UML (Unified Modeling Language) to język modelowania obiektowego, który służy do tworzenia graficznych modeli systemów informatycznych. UML jest szeroko stosowany w procesie projektowania i tworzenia oprogramowania, a także w innych dziedzinach, takich jak przemysł, finanse czy nauka o zarządzaniu.\n Znaczenie UML w procesach tworzenia systemów polega na umożliwieniu lepszego zrozumienia i opisania struktur i procesów zachodzących w danym systemie. Dzięki UML możliwe jest zdefiniowanie wymagań dotyczących systemu, opracowanie jego architektury oraz zaprojektowanie poszczególnych elementów systemu i ich wzajemnych interakcji. UML pozwala również na lepszą komunikację pomiędzy zespołami projektowymi oraz na szybsze i bardziej efektywne wykrywanie i rozwiązywanie problemów w procesie tworzenia systemu."),
        
        Fiszki(name: "Pojęcie i klasyfikacja systemów informacyjnych",
                  description: "System informacyjny to zestaw narzędzi i procesów, które służą do gromadzenia, przetwarzania, przechowywania i udostępniania informacji. Systemy informacyjne są stosowane w różnych dziedzinach, takich jak biznes, administracja, nauka czy służby publiczne.\n Systemy informacyjne można klasyfikować według różnych kryteriów, takich jak:\n Funkcjonalność: Można wyróżnić systemy transakcyjne (które obsługują procesy biznesowe, takie jak sprzedaż czy zamówienia), systemy decyzyjne (które pomagają w podejmowaniu decyzji na podstawie danych), systemy wspomagające zarządzanie (które udostępniają informacje potrzebne do zarządzania przedsiębiorstwem) itp.\n Skala: Można wyróżnić systemy lokalne (które obsługują jedną organizację lub instytucję) i systemy rozproszone (które łączą kilka organizacji lub instytucji).\n Stopień zaawansowania: Można wyróżnić systemy manualne (które opierają się na ręcznym przetwarzaniu danych), systemy elektroniczne (które wykorzystują komputery do przetwarzania danych) i systemy automatyczne (które posiadają wbudowane mechanizmy decyzyjne).\n Obszar zastosowania: Można wyróżnić systemy bazodanowe (które służą do gromadzenia i przechowywania danych), systemy komunikacyjne (które umożliwiają wymianę informacji)."),
        
        Fiszki(name: "Problemy określania niezbędnej liczebności próby",
                  description: "Określenie niezbędnej liczebności próby jest ważnym elementem projektowania badań naukowych. Próba to grupa osób lub obiektów, która jest badana w celu uzyskania informacji na temat całej populacji (czyli grupy, do której próba należy). W celu uzyskania wiarygodnych wyników badania należy dobrać odpowiednią liczebność próby, tak aby była ona reprezentatywna dla całej populacji.\n Problemy, które mogą wystąpić podczas określania niezbędnej liczebności próby, to m.in.:\n Nieznajomość rozkładu cech w populacji: Jeśli nie wiemy, jak rozkładają się poszczególne cechy w populacji (np. płeć, wiek, wykształcenie), trudno jest dobrać odpowiednią liczebność próby.\n Nieznajomość poziomu odchyleń w populacji: Jeśli nie wiemy, jaki jest poziom odchyleń w populacji (czyli jak bardzo poszczególne wartości odstają od średniej), trudno jest dobrać odpowiednią liczebność próby.\n Nieznajomość poziomu dokładności, jaki chcemy osiągnąć: Im większa dokładność, tym większa liczebność próby jest potrzebna.\n Ograniczenia finansowe lub inne praktyczne trudności związane z przeprowadzeniem badania na większej liczebności próby.\n Aby uniknąć tych problemów, należy starannie zaplanować badanie i dokładnie określić jego cel, a następnie dobrać odpowiednią liczebność próby na podstawie dostępnych informacji i ograniczeń."),
        
        Fiszki(name: "Statystyczne testy istotności",
                  description: "Statystyczne testy istotności to narzędzia, które służą do oceny, czy różnice między grupami lub zmiennymi są istotne statystycznie. Testy istotności pozwalają na weryfikację hipotez badawczych, tzn. stwierdzenia, czy dane zaobserwowane w badaniu są zgodne z oczekiwaniami, czy też różnią się od nich na tyle, że można uznać je za istotne.\n Istnieje wiele różnych testów istotności, które różnią się między sobą sposobem obliczania p-value (czyli prawdopodobieństwa, że dane zaobserwowane w badaniu wystąpiłyby przez przypadek). Jeśli p-value jest mniejsze niż ustalony poziom istotności (np. 0,05), oznacza to, że różnice między grupami lub zmiennymi są istotne statystycznie i można odrzucić hipotezę zerową (czyli, że nie ma różnic między grupami lub zmiennymi).\n Przykłady testów istotności to m.in.: test t-Studenta, test złożonego zerowego rozkładu chi-kwadrat, test U Manna-Whitneya, test Fishera. Do wyboru odpowiedniego testu istotności należy brać pod uwagę charakter badanej zmiennej (ciągła czy dyskretna) oraz liczebność i homogeniczność grup."),
        
        Fiszki(name: "Edytory tekstów.",
                  description: "SEdytory tekstu to oprogramowanie służące do tworzenia, edycji i formatowania tekstu. Edytory tekstu są szeroko stosowane w różnych dziedzinach, od pisania dokumentów biurowych po tworzenie kodu źródłowego. Oto kilka przykładów popularnych edytorów tekstu:\n Microsoft Word to popularny edytor tekstu dla systemu Windows. Oferuje szeroki zakres narzędzi do tworzenia i edycji dokumentów, w tym opcje formatowania tekstu, wstawiania obrazów i tabel.\n Google Docs to edytor tekstu dostępny w chmurze, który umożliwia tworzenie i edycję dokumentów online. Można go używać z dowolnego urządzenia z dostępem do internetu.\n Sublime Text to edytor tekstu przeznaczony głównie do tworzenia kodu źródłowego. Posiada szereg narzędzi, takich jak automatyczne uzupełnianie kodu czy podświetlanie składni, które ułatwiają pracę z kodem.\n Notepad++ to kolejny edytor tekstu przeznaczony do tworzenia kodu źródłowego. Jest dostępny dla systemu Windows i oferuje podobne narzędzia jak Sublime Text.\n Vim to edytor tekstu dostępny dla wielu systemów operacyjnych, w tym Linux, macOS i Windows. Jest szczególnie popularny wśród programistów i oferuje szeroki zakres narzędzi do tworzenia i edycji kodu źródłowego."),
        
        Fiszki(name: "Znaczenie skrótów MRP-II, ERP, CRM w odniesieniu do systemów informatycznych w zarządzaniu.",
                  description: "MRP-II (ang. Manufacturing Resource Planning) to system informatyczny służący do planowania zasobów produkcyjnych. MRP-II jest rozszerzeniem systemu MRP (ang. Material Requirements Planning) i umożliwia zarządzanie całym procesem produkcyjnym, od zamówień po dostawy.\n ERP (ang. Enterprise Resource Planning) to system informatyczny służący do zarządzania zasobami przedsiębiorstwa. ERP łączy w jednym systemie różne obszary działalności przedsiębiorstwa, takie jak finanse, księgowość, zarządzanie produkcją, zaopatrzenie czy kadry.\n CRM (ang. Customer Relationship Management) to system informatyczny służący do zarządzania relacjami z klientami. CRM umożliwia zbieranie i analizę danych dotyczących klientów, a także planowanie i realizację działań marketingowych i sprzedażowych.\n MRP-II, ERP i CRM to przykłady systemów informatycznych, które są szeroko stosowane w zarządzaniu przedsiębiorstwem. Pozwalają one zwiększyć efektywność i skuteczność działania, a także umożliwiają lepsze zarządzanie zasobami i relacjami z klientami."),
        
        Fiszki(name: "Kontrola finansowa i audyt wewnętrzny",
                  description: "Kontrola finansowa to proces, w którym sprawdza się prawidłowość i rzetelność danych finansowych oraz zgodność z obowiązującymi przepisami i procedurami. Kontrola finansowa może być prowadzona przez wewnętrzny dział kontroli lub przez zewnętrzne firmy audytorskie.\n Audyt wewnętrzny to rodzaj kontroli finansowej, która jest prowadzona przez wyznaczonych pracowników lub zewnętrznych specjalistów zatrudnionych przez przedsiębiorstwo. Audyt wewnętrzny ma na celu ocenę skuteczności i efektywności działania przedsiębiorstwa oraz zgodności z obowiązującymi przepisami i standardami.\n Kontrola finansowa i audyt wewnętrzny są ważnymi narzędziami zarządzania, które pozwalają zapewnić transparentność i rzetelność działania przedsiębiorstwa oraz zminimalizować ryzyko błędów i nieprawidłowości."),
        
        Fiszki(name: "Geneza i istota Internetu",
                  description: "Internet to globalna sieć połączonych ze sobą komputerów, która umożliwia przesyłanie danych i komunikację między użytkownikami na całym świecie. Internet powstał w latach 60. XX wieku jako projekt badawczy amerykańskiej armii, który miał na celu stworzenie sieci komputerów, która byłaby odporna na awarię i zapewniała możliwość przesyłania danych w razie wojny.\n Geneza Internetu wiąże się z rozwojem sieci komputerowych i technologii komunikacyjnych. W pierwszych latach istnienia Internet składał się z kilku niezależnych sieci komputerowych, które stopniowo połączono w jedną globalną sieć. W latach 80. Internet stał się dostępny dla szerokiej publiczności, a w latach 90. rozpoczął swój dynamiczny rozwój, który trwa do dziś.\n Obecnie Internet jest jednym z najważniejszych narzędzi komunikacyjnych i informacyjnych, umożliwiając dostęp do ogromnych zasobów informacji, usług i aplikacji online. Jest również ważnym narzędziem gospodarczym, umożliwiając m.in. handel i usługi online."),
        
        Fiszki(name: "Systemy ekspertowe, definicja, przykłady.",
                  description: "Systemy ekspertowe to specjalne rodzaje oprogramowania, które są zaprojektowane do automatycznego rozwiązywania złożonych problemów i podejmowania decyzji na podstawie zgromadzonej wiedzy i doświadczenia. Systemy ekspertowe wykorzystują algorytmy sztucznej inteligencji oraz specjalistyczną wiedzę z danej dziedziny, taką jak medycyna czy inżynieria, do rozwiązywania problemów i podejmowania decyzji.\n Systemy ekspertowe są często stosowane w obszarach, w których wymagana jest wiedza specjalistyczna i szybkie podejmowanie decyzji, takich jak diagnostyka medyczna czy planowanie produkcji. Oto kilka przykładów systemów ekspertowych:\n System ekspertowy do diagnostyki medycznej: System ekspertowy do diagnostyki medycznej wykorzystuje algorytmy sztucznej inteligencji do analizy objawów i danych diagnostycznych pacjenta, a następnie sugeruje możliwe rozpoznania i leczenie.\n System ekspertowy do planowania produkcji: System ekspertowy do planowania produkcji wykorzystuje dane dotyczące dostępności surowców i zamówień oraz ograniczeń produkcyjnych, aby zaproponować optymalny plan produkcji.\n System ekspertowy do podejmowania decyzji finansowych: System ekspertowy do podejmowania decyzji finansowych analizuje dane dotyczące sytuacji finansowej przedsiębiorstwa i sugeruje optymalne strategie inwestycyjne lub finansowanie.\n Systemy ekspertowe są coraz powszechniej stosowane w różnych dziedzinach, gdyż umożliwiają automatyzację trudnych i czasochłonnych zadań oraz podejmowanie decyzji na podstawie specjalistycznej wiedzy."),
        
        Fiszki(name: "Funkcje i rodzaje systemów wynagradzania",
                  description: "Systemy wynagradzania są zestawami zasad i procedur, które regulują sposób naliczania i wypłacania wynagrodzeń pracownikom w przedsiębiorstwie. Funkcje systemów wynagradzania to m.in.:\n Motywacyjna: Systemy wynagradzania powinny motywować pracowników do osiągania lepszych wyników i rozwoju zawodowego.\n Sprawiedliwa: Systemy wynagradzania powinny być sprawiedliwe i równe dla wszystkich pracowników, bez względu na ich płeć, rasę czy pochodzenie.\n Efektywna: Systemy wynagradzania powinny być efektywne i przyczyniać się do osiągania celów przedsiębiorstwa.\n Elastyczna: Systemy wynagradzania powinny być elastyczne i uwzględniać indywidualne potrzeby i oczekiwania pracowników.\n Rodzaje systemów wynagradzania to m.in.:\n Wynagrodzenie ryczałtowe: Pracownik otrzymuje stałą kwotę wynagrodzenia, bez względu na ilość pracy lub osiągnięte wyniki.\n Wynagrodzenie godzinowe: Pracownik otrzymuje wynagrodzenie za każdą godzinę pracy.\n Wynagrodzenie za wynik: Pracownik otrzymuje wynagrodzenie zależne od osiągniętych wyników lub wydajności.\n Wynagrodzenie hybrydowe: Łączy elementy kilku rodzajów wynagrodzenia, takie jak wynagrodzenie ryczałtowe i wynagrodzenie za wynik.\n Systemy wynagradzania są ważnym narzędziem zarządzania przedsiębiorstwem, ponieważ odgrywają istotną rolę w motywowaniu pracowników i zapewnianiu sprawiedliwości i efektywności."),
        
        Fiszki(name: "Różnice między podejściem proceduralnym a obiektowym w projektowaniu systemów informatycznych",
                  description: "Podejście proceduralne to sposób projektowania systemów informatycznych, w którym nacisk kładziony jest na procesy i algorytmy, a mniejsze znaczenie ma struktura danych i obiektów. W podejściu proceduralnym program składa się z ciągu instrukcji, które opisują, co system ma robić w danej sytuacji.\n Podejście obiektowe to sposób projektowania systemów informatycznych, w którym nacisk kładziony jest na strukturę danych i obiektów oraz ich relacje i interakcje. W podejściu obiektowym program składa się z obiektów, które posiadają atrybuty (dane) i metody (funkcje), a także mogą komunikować się z innymi obiektami.\n Oto kilka głównych różnic między podejściem proceduralnym a obiektowym:\n Struktura danych: W podejściu proceduralnym struktura danych jest mniej ważna niż algorytmy, natomiast w podejściu obiektowym struktura danych jest kluczowa i oparta na obiektach.\n Modularność: Podejście proceduralne często prowadzi do tworzenia monolitycznych programów, natomiast podejście obiektowe umożliwia tworzenie bardziej modularnych programów, składających się z niezależnych obiektów."),
        
        Fiszki(name: "Podstawowe zasady rachunkowości",
                  description: "Rachunkowość jest dziedziną nauki, która zajmuje się zbieraniem, przechowywaniem i interpretacją danych finansowych. Podstawowe zasady rachunkowości to:\nZasada rzetelności: Wszystkie dane finansowe powinny być rzetelne i wiarygodne.\nZasada użyteczności: Informacje finansowe powinny być użyteczne i przydatne dla osób, które z nich korzystają.\nZasada sprawiedliwości: Wszystkie transakcje powinny być wycenione w sposób sprawiedliwy i obiektywny.\nZasada odpowiedzialności: Wszystkie transakcje powinny być rejestrowane i przypisane odpowiednim podmiotom.\nZasada przejrzystości: Informacje finansowe powinny być jasno i czytelnie przedstawione.\nZasada równoważności: Wszystkie transakcje powinny być rejestrowane w obu kierunkach (np. koszty powinny być ujęte wraz z przychodami)."),
        
        Fiszki(name: "Istota metody reprezentacyjnej, populacja generalna i próba",
                  description: "Metoda reprezentacyjna to sposób badania dużych grup ludzi, tzw. populacji generalnej, poprzez próbę, czyli mniejszą grupę osób, która ma reprezentować całą populację. Celem metody reprezentacyjnej jest wyciągnięcie wniosków na temat całej populacji na podstawie badania próby.\nPopulacja generalna to cała grupa osób, która spełnia określone kryteria i jest przedmiotem badań.\nPróba to mniejsza grupa osób, która jest reprezentatywna dla całej populacji i jest badana w celu wyciągnięcia wniosków na temat całej populacji. Aby próba była reprezentatywna, należy ją dobierać tak, aby jej skład odpowiadał składowi populacji generalnej pod względem takich czynników, jak wiek, płeć, pochodzenie etniczne itp.\nMetoda reprezentacyjna jest stosowana w wielu dziedzinach, takich jak socjologia, marketingu, medycyna czy polityka, w celu uzyskania wiarygodnych wyników badań na temat danej populacji."),
        
        Fiszki(name: "Przykłady liniowych i nieliniowych problemów optymalizacyjnych.",
                  description: "Liniowe problemy optymalizacyjne to takie, w których funkcja celu oraz ograniczenia są liniowe. Przykłady takich problemów to:\nMinimalizacja kosztów produkcji przy określonym zapotrzebowaniu na poszczególne produkty.\nMaksymalizacja zysku przy określonych ograniczeniach produkcji i zapotrzebowaniu na produkty.\nNieliniowe problemy optymalizacyjne to takie, w których funkcja celu lub ograniczenia są nieliniowe. Przykłady takich problemów to:\nOptymalizacja trasy podróży samochodem, uwzględniając ograniczenia terenowe oraz koszty paliwa.\nOptymalizacja projektu budowlanego, uwzględniając ograniczenia terenowe oraz koszty materiałów i robocizny."),
        
        Fiszki(name: "Różnice między grafiką rastrową i wektorową",
                  description: "Grafika rastrowa (bitmapowa) to sposób przedstawiania obrazów, w którym obraz jest składany z kolorowych pikseli (punctiforms). Każdy piksel jest indywidualnym elementem obrazu i jest reprezentowany przez określoną liczbę bitów, która określa jego kolor. Grafika rastrowa jest dobra do przedstawiania szczegółowych obrazów, takich jak zdjęcia.\nGrafika wektorowa to sposób przedstawiania obrazów, w którym obraz jest składany z kształtów i linii. Kształty i linie są opisane przez algorytmy i są niezależne od rozdzielczości. Dzięki temu obrazy wektorowe są elastyczne i mogą być łatwo skalowane bez utraty jakości. Grafika wektorowa jest dobra do tworzenia prostych, precyzyjnych kształtów i linii, takich jak loga czy ikony.\nOto kilka głównych różnic między grafiką rastrową a wektorową:\nStruktura: Grafika rastrowa składa się z pikseli, natomiast grafika wektorowa składa się z kształtów i linii opisanych przez algorytmy.\nSkalowalność: Grafika rastrowa traci jakość po skalowaniu, natomiast grafika wektorowa jest elastyczna i może być skalowana bez utraty jakości.\nZastosowanie: Grafika rastrowa jest dobra do przedstawiania szczegółowych obraz"),
        Fiszki(name: "Bloki funkcjonalne komputera",
                  description: "Bloki funkcjonalne komputera to poszczególne podzespoły lub układy, które wspólnie tworzą pełniącą swoje zadania jednostkę. Oto niektóre z podstawowych bloków funkcjonalnych komputera:\nProcesor (CPU) - serce komputera, odpowiedzialny za przetwarzanie danych.\nPamięć RAM - pamięć, w której przechowywane są dane i programy, które są w danej chwili wykorzystywane przez procesor.\nDysk twardy (HDD) lub dysk SSD - magazyn danych, w którym przechowywane są pliki i programy, nawet po wyłączeniu komputera.\nKarta graficzna (GPU) - układ odpowiedzialny za przetwarzanie i wyświetlanie obrazu na ekranie.\nZłącza rozszerzeń - umożliwiają podłączenie do komputera różnych urządzeń zewnętrznych, takich jak mysz, klawiatura, drukarka itp.\nNapęd optyczny - umożliwia odczyt i zapis danych na płytach CD, DVD lub Blu-ray.\nZasilacz - dostarcza prądu do poszczególnych podzespołów komputera.\nObudowa - chroni wszystkie podzespoły komputera i umożliwia ich montaż."),
        
        Fiszki(name: "Modele cyklu życia systemu informatycznego.",
                  description: "Modele cyklu życia systemu informatycznego (ang. software development life cycle, SDLC) to ramy koncepcyjne, które opisują etapy tworzenia i utrzymania systemu informatycznego. Różne modele SDLC różnią się między sobą podejściem do procesu tworzenia systemu, a także zakresem i poziomem szczegółowości poszczególnych etapów. Oto kilka przykładów modeli SDLC:\nModel linii prostej (ang. waterfall model) - jest to jeden z najstarszych modeli SDLC, w którym etapy tworzenia systemu są realizowane kolejno, bez możliwości powrotu do poprzednich etapów. Każdy etap musi być zakończony zanim rozpocznie się kolejny.\nModel V (ang. V-model) - jest to ulepszona wersja modelu linii prostej, w której każdy etap tworzenia systemu jest połączony z odpowiednim etapem testowania. Dzięki temu możliwe jest wczesne wykrywanie błędów i ich usuwanie.\nModel iteracyjny (ang. iterative model) - jest to model, w którym etapy tworzenia systemu są realizowane wielokrotnie, aż do osiągnięcia pożądanego poziomu jakości. Każda iteracja składa się z kilku etapów projektowania, implementacji i testowania.\nModel spiralny (ang. spiral model) - jest to model, w którym etapy tworzenia systemu są realizowane iteracyjnie, ale każda iteracja jest bardziej szczegółowa niż poprzednia. Model spiralny uwzględnia także ryzyka związane z projektem i opracowuje strategie ich zarządzania.\nModel Agile - jest to zbiór metodologii zwinnych, które umożliwiają szybkie reagowanie na zmiany i elastyczne dostosowywanie się do potrzeb klienta. W modelu Agile etapy tworzenia systemu są realizowane iteracyjnie, a klient jest aktywnym uczestnikiem procesu."),
        
        Fiszki(name: "Podstawowe mierniki wzrostu i rozwoju gospodarczego krajów (PKB, PNB, DN)",
                  description: "PKB (ang. gross domestic product, PKB) to wskaźnik, który określa wartość wszystkich dóbr i usług finalnych wyprodukowanych w danym kraju w ciągu roku. PKB jest często używany jako miernik wzrostu i rozwoju gospodarczego kraju.\nPNB (ang. gross national product, PNB) to wskaźnik, który określa wartość wszystkich dóbr i usług finalnych wyprodukowanych przez obywateli danego kraju w ciągu roku, niezależnie od tego, gdzie są one produkowane. PNB uwzględnia także dochody zagraniczne i podatki od nich pobierane.\nDN (ang. GDP per capita, GDP/capita) to wskaźnik, który określa wartość PKB na jednego mieszkańca danego kraju. Jest to miernik, który pozwala porównać poziom rozwoju gospodarczego różnych krajów.\nOprócz PKB, PNB i DN istnieją także inne mierniki wzrostu i rozwoju gospodarczego krajów, takie jak np. indeks rozwoju ludzkiego (Human Development Index, HDI) czy wskaźnik Gini. Każdy z tych mierników ma swoje wady i zalety i może być używany do oceny sytuacji gospodarczej kraju z różnych perspektyw."),
        
        Fiszki(name: "Sposoby pomiaru współzależności zjawisk",
                  description: "Istnieje wiele sposobów pomiaru współzależności zjawisk, takich jak korelacja, regresja czy analiza skupień. Oto krótki opis każdego z nich:\nKorelacja - jest to miernik, który określa, czy istnieje związek między dwoma zmiennymi. Może być obliczana na podstawie różnych miar korelacji, takich jak korelacja Pearsona, korelacja Spearmana czy korelacja Kendalla. Im wyższa wartość korelacji, tym silniejszy związek między zmiennymi.\nRegresja - jest to metoda statystyczna, która pozwala na przewidzenie wartości jednej zmiennej na podstawie wartości innej zmiennej. Można ją stosować, gdy istnieje liniowa zależność między zmiennymi.\nAnaliza skupień - jest to metoda statystyczna, która pozwala na grupowanie obiektów (np. ludzi, firm) według podobieństwa ich cech. Można ją stosować, gdy chcemy znaleźć podobne do siebie grupy zjawisk lub zidentyfikować różnice między nimi.\nInne sposoby pomiaru współzależności zjawisk to m.in. analiza korespondencji, analiza wariancji, analiza skojarzeń. Każdy z nich ma swoje zastosowanie w zależności od rodzaju danych i celu badania."),
        
        Fiszki(name: "Role serwerów w sieciach typu klient - serwer",
                  description: "Oto kilka przykładów ról, jakie mogą pełnić serwery w sieciach typu klient-serwer:\nSerwer plików - służy do udostępniania plików i folderów użytkownikom sieci. Może być wykorzystywany do przechowywania dokumentów, obrazów, filmów itp.\nSerwer baz danych - służy do przechowywania i zarządzania danymi, takimi jak np. informacje o klientach, produktach czy zamówieniach. Może być wykorzystywany przez aplikacje klienckie do odczytu lub zapisu danych.\nSerwer WWW - służy do udostępniania zasobów sieciowych, takich jak strony internetowe, obrazki czy pliki multimedialne. Użytkownicy mogą uzyskać dostęp do tych zasobów poprzez przeglądarkę internetową.\nSerwer poczty elektronicznej - służy do przesyłania i odbierania wiadomości elektronicznych. Może być wykorzystywany zarówno przez aplikacje klienckie, jak i przez przeglądarkę internetową.\nSerwer aplikacji - służy do udostępniania aplikacji klientom sieci. Użytkownicy mogą korzystać z aplikacji zdalnie, za pośrednictwem klienta aplikacji lub przeglądarki internetowej.\nSerwery w sieciach typu klient-serwer pełnią ważną rolę w zapewnieniu sprawnego funkcjonowania sieci oraz udostępniania różnego rodzaju zasobów i usług użytkownikom."),
        
        Fiszki(name: "Metody badań operacyjnych jako narzędzia wspierające analizy decyzyjne",
                  description: "Metody badań operacyjnych (ang. operations research, OR) to dziedzina nauki, która zajmuje się rozwiązywaniem problemów decyzyjnych za pomocą narzędzi matematycznych i informatycznych. Metody te są szczególnie przydatne w sytuacjach, gdy problem decyzyjny jest złożony i wymaga rozważenia wielu czynników oraz ograniczeń.\nMetody badań operacyjnych mogą być wykorzystywane jako narzędzia wspierające analizy decyzyjne w różnych dziedzinach, takich jak analizach np. zarządzanie, finanse, logistyka, marketing itp. Oto kilka przykładów zastosowań metod badań operacyjnych w decyzyjnych:\nModelowanie matematyczne - pozwala na opisanie problemu decyzyjnego w formie matematycznej, co umożliwia wyznaczenie optymalnych rozwiązań za pomocą algorytmów matematycznych.\nProgramowanie liniowe - umożliwia znajdowanie optymalnych rozwiązań problemów decyzyjnych, które obejmują ograniczenia liniowe.\nSymulacja komputerowa - pozwala na symulowanie różnych scenariuszy i wyliczenie ich skutków na podstawie danych historycznych lub szacunków.\nAnaliza decyzji - umożliwia ocenę ryzyka i wartości opcji decyzyjnych za pomocą narzędzi matematycznych i statystycznych.\nMetody badań operacyjnych stanowią cenne narzędzie wspierające proces podejmowania decyzji w różnych sytuacjach, zarówno w biznesie, jak i w innych dziedzinach."),
        
        Fiszki(name: "Pojęcie, metody pomiaru, przyczyny, rodzaje i ekonomiczne skutki bezrobocia",
                  description: "Bezrobocie to stan, w którym osoby aktywne zawodowo nie są zatrudnione, ale są gotowe do podjęcia pracy i szukają zatrudnienia. Bezrobocie może być mierzone na różne sposoby, a jednym z najczęściej stosowanych jest stopa bezrobocia, która określa procent osób bez pracy w stosunku do całej ludności w wieku produkcyjnym.\nIstnieje wiele przyczyn bezrobocia, takich jak np. kryzysy gospodarcze, zmiany technologiczne, zmiany w strukturze rynku pracy, brak odpowiednich kwalifikacji czy bariery geograficzne. Bezrobocie może być także skutkiem indywidualnych decyzji, takich jak np. rezygnacja z pracy w celu podjęcia nauki lub opieki nad dziećmi.\nIstnieją różne rodzaje bezrobocia, takie jak bezrobocie strukturalne, sezonowe, technologiczne czy cykliczne. Bezrobocie strukturalne wynika z dysproporcji między poszukiwanymi kwalifikacjami a dostępnymi ofertami pracy. Bezrobocie sezonowe dotyczy branż, w których sezonowość ma wpływ na poziom zatrudnienia, np. turystyka czy rolnictwo. Bezrobocie technologiczne wynika z wprowadzenia nowych technologii, które zastępują ludzi w procesie produkcji."),
        
        Fiszki(name: "Cechy charakterystyczne współczesnych kryzysów finansowych i ekonomicznych",
                  description: "Współczesne kryzysy finansowe i ekonomiczne charakteryzują się kilkoma cechami, które odróżniają je od kryzysów sprzed lat. Oto niektóre z nich:\nSzybkość rozprzestrzeniania się - kryzysy finansowe są coraz bardziej globalne i szybko rozprzestrzeniają się na inne rynki i sektory gospodarki.\nZłożoność - współczesne kryzysy finansowe są zazwyczaj bardzo złożone i mogą mieć różne przyczyny, takie jak np. brak regulacji rynkowych, nadmierne zadłużenie, brak transparentności czy brak odpowiedzialności instytucji finansowych.\nGlobalne skutki - kryzysy finansowe i ekonomiczne mogą mieć bardzo szerokie skutki, dotykając nie tylko sektora finansowego, ale także innych sektorów gospodarki, takich jak np. przemysł czy usługi.\nTrudności w rozwiązaniu - kryzysy finansowe są trudne do rozwiązania, ponieważ wymagają skoordynowanej reakcji różnych podmiotów (rządów, instytucji finansowych, firm itp.) i często wymagają podjęcia trudnych decyzji.\nCzęstotliwość występowania - kryzysy finansowe i ekonomiczne występują coraz częściej, co wynika m.in. z globalizacji rynków i coraz większej złożoności mechanizmów rynkowych."),
        
        Fiszki(name: "ZAGADNIENIA SPECJALISTYCZNE", description: "część zagadnień specjalistycznych"),
        
        Fiszki(name: "Proszę omówić pojęcie gry i zabawy w naukach społecznych",
                  description: "W naukach społecznych pojęcie gry i zabawy odnosi się do różnych form interakcji między ludźmi, które mają charakter celowy, ale nie są związane z codziennymi obowiązkami i obciążeniami. Gry i zabawy mogą mieć różne formy i mogą być realizowane w różnych miejscach, takich jak np. szkoła, praca, dom czy park.\nGry i zabawy pełnią ważną rolę w życiu społecznym i kulturze. Służą m.in. do nawiązywania relacji między ludźmi, do rozwijania umiejętności społecznych i komunikacyjnych, a także do zapewnienia rozrywki i odpoczynku.\nW naukach społecznych pojęcie gry i zabawy jest również często używane jako metafora do opisywania różnych form interakcji i działań społecznych, takich jak np. polityka czy biznes. W ten sposób gry i zabawy stają się narzędziem do analizy i zrozumienia różnych mechanizmów i procesów społecznych."),
        
        Fiszki(name: "Proszę omówić rozwój technologiczny gier",
                  description: "Rozwój technologiczny gier rozpoczął się w latach 50. i 60. XX wieku, kiedy pojawiły się pierwsze komputery osobiste i konsole do gier. W ciągu ostatnich kilku dekad technologia gier znacząco się rozwinęła i obecnie mamy do czynienia z bardzo zaawansowanymi i złożonymi produktami.\nJednym z kluczowych elementów rozwoju technologicznego gier była ewolucja oprogramowania. W miarę jak komputery stawały się coraz potężniejsze, twórcy gier mogli tworzyć coraz bardziej złożone i realistyczne światy. Oprócz tego pojawiły się także nowe rodzaje oprogramowania, takie jak np. engine'y, które umożliwiają szybsze i łatwiejsze tworzenie gier.\nInnym ważnym elementem rozwoju technologicznego gier była ewolucja sprzętu do gier. Konsole do gier stały się coraz potężniejsze, a pojawienie się urządzeń takich jak smartfony i tablety umożliwiło grę na urządzeniach mobilnych. W ostatnich latach pojawiły się także nowe technologie, takie jak np. wirtualna rzeczywistość, które otwierają nowe możliwości rozgrywki.\nRozwój technologiczny gier ma również wpływ na sposób, w jaki gry są tworzone i dystrybuowane. W dobie internetu coraz więcej gier jest dostępnych w formie cyfrowej, co umożliwia szybki i łatwy dostęp do gier z całego świata."),
        
        Fiszki(name: "Proszę omówić rozwój gatunkowy gier",
                  description: "Gatunki gier są to rodzaje gier, które różnią się między sobą pod względem mechanik rozgrywki, sposobu prezentacji, tematyki czy celu gry.\nRozwój gatunkowy gier rozpoczął się wraz z pojawieniem się pierwszych komputerów osobistych i konsol do gier. W ciągu ostatnich kilku dekad pojawiły się różne nowe gatunki gier, a istniejące gatunki ewoluowały i rozwijały się.\nJednymi z pierwszych gatunków gier były gry zręcznościowe, takie jak np. Space Invaders czy Pac-Man, oraz gry fabularne, takie jak np. Zork. W kolejnych latach pojawiły się nowe gatunki, takie jak np. gry strategiczne, taktyczne, RPG (gry fabularne z elementami rozgrywki fabularnej), FPS (gry strzelanki pierwszoosobowe) czy MMO (gry sieciowe z rozgrywką dla wielu graczy).\nObecnie istnieje wiele różnych gatunków gier, a granice między nimi są coraz mniej wyraźne. Wiele gier łączy elementy kilku różnych gatunków, tworząc nowe, hybrydowe formy rozgrywki."),
        
        Fiszki(name: "Proszę omówić ekonomiczne znaczenie gier",
                  description: "Gry mają istotne znaczenie ekonomiczne, ponieważ mogą wpływać na różne aspekty rynku i gospodarki.\nStanowią ważny element rynku rozrywki i rekreacji, co przyciąga wielu konsumentów i generuje duże przychody dla przemysłu gier.\nMogą być również ważnym źródłem inwestycji, zarówno dla indywidualnych inwestorów, jak i dla instytucjonalnych.\nSą często wykorzystywane w edukacji i treningu, ponieważ pozwalają na interaktywne przyswajanie wiedzy i rozwijanie umiejętności.\nPrzemysł gier jest często motorem napędowym rozwoju nowych technologii, takich jak grafika komputerowa czy sztuczna inteligencja.\nSą również ważnym narzędziem badawczym w ekonomii eksperymentalnej, ponieważ pozwalają na badanie zachowań ekonomicznych w warunkach laboratoryjnych.\nMogą również wpływać na rozwój gospodarczy, jak rozwój gier na platformy mobilne, które mogą rozwijać miejsca pracy i przedsiębiorstwa.\nPrzemysł gier jest również ważnym źródłem zatrudnienia, zarówno w dziedzinie tworzenia gier, jak i w dziedzinie sprzedaży i marketingu."),
        
       // Fiszki(name: "Sposoby wykorzystania gier w edukacji, nauce",
                
       //        description: "stnieje wiele sposobów wykorzystania gier w edukacji i nauce. Oto kilka przykładów:\nGry edukacyjne: Są to specjalnie zaprojektowane gry, które mają na celu nauczanie konkretnych umiejętności lub przedmiotów. Przykłady takich gier to gry do nauki matematyki, języków obcych czy przedmiotów ścisłych.\nGry symulacyjne: Służą one do symulowania rzeczywistych sytuacji, zjawisk czy procesów, pozwalają na zrozumienie złożonych zagadnień poprzez bezpośrednie doświadczenie.\nGry problemowe: polegają na rozwiązywaniu problemów, rozwiązywaniu zadań, rozwiązywaniu zagadek, itp.\nGry fabularne: polegają na przeżywaniu przygód, rozwiązywaniu zagadek, itp.\nGry RPG (role-playing game): polegają na odgrywaniu ról, rozwiązywaniu zadań, itp.\nGry współpracy: polegają na współpracy z innymi graczami, rozwiązywaniu zadań, itp.\nGry sieciowe: polegają na graniu z innymi graczami przez internet, rozwiązywaniu zadań, itp.\nGry mobilne: polegają na graniu na urządzeniach mobilnych, rozwiązywaniu zadań, itp.\mTakie gry edukacyjne i symulacyjne pozwalają na przyswajanie wiedzy w atrakcyjny i angażujący sposób, co prowadzi do lepszego przyswajania wiedzy i zwiększa zainteresowanie przedmiotem.\n Jednym z przykładów gier edukacyjnych jest Civilization VI, która jest strategią czasu rzeczywistego pozwalającą na symulowanie rozwoju cywilizacji. Gra ta jest często wykorzystywana w klasach historii i geografii do nauki o rozwoju cywilizacji, relacjach między państwami, polityce itp.\n Innym przykładem jest Minecraft Education Edition jest specjalna edycja gry Minecraft, która jest przeznaczona dla nauczycieli i uczniów. Ta edycja zawiera specjalne narzędzia i zestawy lekcji, które pozwalają na nauczanie matematyki, fizyki, chemii, geografii i innych przedmiotów.\nKolejnym przykładem jest gra Foldit jest grą edukacyjną przeznaczoną do nauki biologii. Gracze wykorzystują swoją wiedzę z zakresu biologii do rozwiązywania zagadek związanych z rozwiązywaniem struktur białek.\nTe przykłady pokazują jak gry mogą być skutecznie wykorzystywane w edukacji do nauki różnych przedmiotów i zagadnień."),
        
        Fiszki(name: "Proszę wymienić kluczowe koncepcje związane z narracja i opowiadaniem historii",
                  description: "Narracja i opowiadanie historii to ważne koncepcje w wielu dziedzinach, w tym w literaturze, filmie, grach komputerowych czy reklamie. Oto kilka kluczowych koncepcji związanych z narracją i opowiadaniem historii:\nFabuła: Fabuła to struktura opowiadanej historii, która obejmuje wydarzenia, postaci i ich motywacje oraz sposób, w jaki te elementy są ze sobą powiązane.\nPerspektywa narracyjna: Perspektywa narracyjna określa sposób, w jaki historia jest opowiadana, tj. z punktu widzenia określonej postaci czy z perspektywy obserwatora zewnętrznego.\nPunkt widzenia: Punkt widzenia to perspektywa, z której opowiadana jest historia, tj. punkt widzenia określonej postaci lub grupy postaci.\nStruktura narracji: Struktura narracji to sposób, w jaki historia jest opowiadana, tj. sekwencja wydarzeń, sposób ich ujęcia oraz relacje między nimi.\nKompozycja narracji: Kompozycja narracji to sposób, w jaki elementy fabuły i struktury narracji są ze sobą połączone i tworzą spójną całość.\nSposób opowiadania: Sposób opowiadania to styl, w jaki historia jest przedstawiona, tj. sposób użycia języka, emocji czy szczegółów.\nPunkt zwrotny: Punkt zwrotny to moment w opowiadanej historii, w którym następuje zmiana kierunku lub istotny przełom."),
        
        Fiszki(name: "Proszę omówić fabuły liniowe",
                  description: "Fabuła liniowa to rodzaj struktury opowiadanej historii, w której wydarzenia są opowiadane w kolejności chronologicznej. W takiej fabule wszystkie wydarzenia są ze sobą ściśle powiązane i tworzą spójną całość. Fabuła liniowa jest często stosowana w różnych formach narracji, takich jak literatura, film czy gry komputerowe.\nPrzykłady fabuł liniowych to np. opowieści o poszukiwaniu skarbu, odkrywaniu tajemnicy czy przeżywaniu przygód. W takich opowieściach wydarzenia są opowiadane kolejno, od początku do końca, co pozwala na lepsze zrozumienie historii i jej sensu.\nFabuły liniowe są często wykorzystywane w grach komputerowych, ponieważ umożliwiają one lepsze zaprezentowanie historii i zapewniają spójność całej rozgrywki.\nJedną z głównych zalet fabuł liniowych jest ich prostota i łatwość zrozumienia przez odbiorcę. W przeciwieństwie do fabuł nieliniowych, w których wydarzenia są opowiadane w różnych kolejnościach, fabuły liniowe są łatwiejsze do zrozumienia i pozwalają na lepsze zapamiętanie historii."),
        
        Fiszki(name: "Proszę omówić fabuły nieliniowe",
                  description: "Fabuła nieliniowa to rodzaj struktury opowiadanej historii, w której wydarzenia są opowiadane w niekoniecznej kolejności chronologicznej. W takiej fabule wydarzenia mogą być opowiadane w różnych porządkach lub mogą być pomieszane z innymi wydarzeniami, co tworzy bardziej skomplikowaną i nieliniową historię.\nFabuły nieliniowe są często stosowane w literaturze, filmie czy grach komputerowych. Przykłady fabuł nieliniowych to np. opowieści o zagadkach, tajemnicach czy historie z przeszłości, które są opowiadane w różnych porządkach lub są pomieszane z wydarzeniami z innych okresów czasu.\nFabuły nieliniowe są często wykorzystywane w grach komputerowych, ponieważ pozwalają one na bardziej złożone i interesujące historie oraz umożliwiają graczowi większą swobodę wyboru.\nJedną z głównych zalet fabuł nieliniowych jest ich różnorodność i możliwość tworzenia bardziej skomplikowanych i interesujących historii. W przeciwieństwie do fabuł liniowych, które są łatwiejsze do zrozumienia, fabuły nieliniowe mogą być bardziej skomplikowane i wymagać większego zaangażowania od odbiorcy."),
        
        Fiszki(name: "Proszę wymienić omówić oprogramowanie do projektowania 3D",
                  description: "Oprogramowanie do projektowania 3D to narzędzia, które służą do tworzenia trójwymiarowych modeli i animacji. Są one często wykorzystywane w różnych dziedzinach, takich jak grafika komputerowa, architektura, inżynieria czy gry komputerowe. Niektóre przykłady oprogramowania do projektowania 3D to:\nAutodesk 3ds Max - profesjonalne narzędzie do tworzenia animacji i modeli 3D. Zawiera szerokie możliwości edycji i tworzenia efektów specjalnych oraz integrację z innymi narzędziami Autodesk.\nBlender - darmowe oprogramowanie o otwartym kodzie źródłowym do tworzenia modeli 3D, animacji i filmów. Zawiera szerokie możliwości edycji i tworzenia efektów specjalnych oraz szeroki zakres narzędzi do modelowania i animacji.\nCinema 4D - profesjonalne narzędzie do tworzenia animacji i modeli 3D. Zawiera szerokie możliwości edycji i tworzenia efektów specjalnych oraz integrację z innymi narzędziami firmy Maxon.\nSketchUp - prosta w obsłudze aplikacja do tworzenia modeli 3D. Służy głównie do tworzenia prostych modeli architektonicznych i wnętrz.\nZBrush - narzędzie do tworzenia szczegółowych modeli 3D z wysokim poziomem szczegółowości. Zawiera szerokie możliwości edycji i tworzenia efektów specjalnych oraz szeroki zakres narzędzi do modelowania i animacji."),
        
        Fiszki(name: "Tworzenie animacji dla stron WWW",
                  description: "Tworzenie animacji dla stron WWW to proces tworzenia dynamicznych elementów na stronach internetowych, które mogą być wyświetlane w przeglądarkach internetowych. Animacje mogą być tworzone za pomocą różnych technik, takich jak CSS, JavaScript, HTML5 czy Flash.\nTworzenie animacji dla stron WWW wymaga znajomości podstawowych zasad tworzenia animacji oraz zastosowania odpowiednich narzędzi i technik. Najczęściej używanymi narzędziami do tworzenia animacji są programy graficzne, takie jak Adobe Photoshop czy Adobe Illustrator, a także specjalistyczne narzędzia do tworzenia animacji, takie jak Adobe After Effects czy Blender.\nTworzenie animacji dla stron WWW polega na przygotowaniu odpowiednich grafik i sekwencji animacji, a następnie ich zamieszczenie na stronie internetowej za pomocą odpowiednich technik. Możliwe jest również zastosowanie gotowych narzędzi do tworzenia animacji, takich jak kreatory animacji dostępne w internecie."),
        
        Fiszki(name: "Grafika rastrowa – charakterystyka, wady i zalety, przykłady użycia",
                  description: "Grafika rastrowa (bitmapowa) to rodzaj grafiki, w której obraz jest reprezentowany przez siatkę komórek (pikseli), a każdy z nich ma przypisany kolor. W zależności od ilości pikseli, które tworzą obraz, rozróżnia się grafikę rastrową o wysokiej i niskiej rozdzielczości. Grafika rastrowa o wysokiej rozdzielczości jest bardziej szczegółowa i ma lepszą jakość, ale też zajmuje więcej miejsca na dysku.\nGrafika rastrowa ma wiele zastosowań w różnych dziedzinach. Jest często używana do tworzenia zdjęć, obrazów ogólnego przeznaczenia oraz obrazów zawierających dużo szczegółów. Może być również używana do tworzenia animacji, choć jest to trudniejsze niż w przypadku grafiki wektorowej.\nGrafika rastrowa ma również pewne wady. Przede wszystkim, ze względu na dużą liczbę pikseli, obraz zajmuje dużo miejsca na dysku i może być ciężki do przesłania przez internet. Ponadto, ze względu na to, że obraz jest reprezentowany przez piksele, trudno jest go powiększać bez utraty jakości. Gdy obraz jest powiększany, piksele są rozciągane, co prowadzi do pogorszenia jakości obrazu. Przykłady użycia grafiki rastrowej to:\nZdjęcia\nObrazy ogólnego przeznaczenia (np. plakaty, reklamy)\nMapy\nIkony\nEmblematy\nAnimacje (choć rzadziej niż w przypadku grafiki wektorowej)"),
        
        Fiszki(name: "Grafika wektorowa – charakterystyka, wady i zalety, przykłady użycia",
                  description: "Grafika wektorowa to rodzaj grafiki, w której obraz jest reprezentowany przez różnego rodzaju kształty i figury geometryczne, takie jak linie, okręgi, elipsy, trójkąty itp. Każdy z tych kształtów jest opisany przez matematyczne wzory, dzięki czemu obraz jest reprezentowany przez wektory (ciągi liczb opisujących położenie punktów).\nGrafika wektorowa ma wiele zalet w stosunku do grafiki rastrowej. Przede wszystkim, ze względu na brak pikseli, obraz zajmuje znacznie mniej miejsca na dysku i jest łatwiejszy do przesłania przez internet. Ponadto, ze względu na to, że obraz jest opisany przez wzory, można go łatwo skalować bez utraty jakości. W przeciwieństwie do grafiki rastrowej, grafika wektorowa nie traci jakości podczas powiększania, ponieważ kształty są opisywane przez wzory, a nie przez poszczególne piksele.\nGrafika wektorowa ma również pewne wady. Przede wszystkim, jest mniej szczegółowa niż grafika rastrowa i nie nadaje się do prezentowania obrazów o dużej liczbie szczegółów. Ponadto, grafika wektorowa nie jest dobrym rozwiązaniem do tworzenia animacji, ponieważ wymaga dużo więcej obliczeń niż grafika rastrowa. Przykłady użycia grafiki wektorowej to:\nIkony\nLoga\nDiagramy\nWizualizacje danych \nProjekty graficzne (np. plakaty, ulotki)\nMapy\nAnimacje (choć rzadziej niż w przypadku grafiki rastrowej)"),
        
        Fiszki(name: "Metody montażu muzyki na potrzeby gier",
                  description: "Montaż muzyki na potrzeby gier to proces tworzenia oprawy muzycznej do gry komputerowej lub konsolowej. Istnieje kilka różnych metod montażu muzyki, które mogą być używane w zależności od potrzeb danej gry. Oto kilka przykładów:\nMontaż pod konkretne wydarzenia w grze: Muzyka jest dostosowywana do konkretnych wydarzeń w grze, takich jak walka z bossami, skoki na platformach itp. Może być to realizowane poprzez dodawanie odpowiednich fragmentów muzyki lub przez zmianę parametrów muzyki (np. tempo, nastrój).\nMontaż dynamiczny: Muzyka jest dostosowywana do tego, co dzieje się w grze w czasie rzeczywistym. Na przykład, gdy gracz porusza się w wolnym tempie, muzyka może być spokojna i nastrojowa, a gdy gracz zaczyna walczyć, muzyka może się przyspieszyć i stać się bardziej ekscytująca.\nMontaż z użyciem specjalnych efektów: Muzyka może być wzbogacona o specjalne efekty dźwiękowe, takie jak odgłosy walki, wybuchy itp., które są dostosowywane do akcji w grze.\nMontaż z użyciem muzyki oryginalnej: Muzyka oryginalna jest tworzona specjalnie dla danej gry i jest nierozerwalnie związana z nią. Może być ona używana jako oprawa muzyczna całej gry lub w określonych momentach."),
        
        Fiszki(name: "Działanie i ograniczenia urządzeń mobilnych",
                  description: "Urządzenia mobilne to urządzenia elektroniczne, które można swobodnie przenosić i korzystać z nich w różnych miejscach. Do najpopularniejszych urządzeń mobilnych należą smartfony, tablety, komputery przenośne (laptopy) i konsole do gier.\nDziałanie urządzeń mobilnych jest uzależnione od ich rodzaju i specyfikacji technicznej. Ogólnie rzecz biorąc, urządzenia mobilne są wyposażone w procesor, pamięć RAM, dysk twardy lub pamięć wewnętrzną oraz wyświetlacz. Są one zasilane przez baterie lub akumulatory, które umożliwiają korzystanie z urządzenia przez pewien czas po odłączeniu go od zasilania sieciowego.\nOgraniczenia urządzeń mobilnych zależą od ich specyfikacji technicznej i rodzaju zastosowania. Na przykład, smartfony i tablety są ograniczone przez pojemność baterii, co oznacza, że po pewnym czasie korzystania z urządzenia trzeba je ładować. Innym ograniczeniem może być pojemność dysku twardego lub pamięci wewnętrznej, co oznacza, że na urządzeniu nie można zapisać zbyt dużej ilości danych.\nPonadto, urządzenia mobilne są ograniczone przez rodzaj i szybkość łącza internetowego, co wpływa na to, jak szybko można pobierać dane lub korzystać z aplikacji internetowych."),
        
        Fiszki(name: "Specyfika programowania urządzeń mobilnych oraz modele dystrybucji oprogramowania",
                  description: "Programowanie urządzeń mobilnych to proces tworzenia oprogramowania (aplikacji) dedykowanego dla urządzeń mobilnych, takich jak smartfony, tablety czy konsole do gier. W przypadku programowania urządzeń mobilnych, istotne jest zrozumienie specyfiki tych urządzeń oraz ograniczeń, z jakimi się je ma do czynienia.\nJednym z głównych ograniczeń jest ograniczona moc obliczeniowa urządzeń mobilnych w porównaniu do komputerów stacjonarnych. Oznacza to, że aplikacje mobilne muszą być zoptymalizowane pod kątem wydajności, aby działały płynnie i nie obciążały zbytnio urządzenia.\nKolejnym ważnym aspektem jest interfejs użytkownika (UI) oraz doświadczenie użytkownika (UX). W przypadku urządzeń mobilnych, interfejs musi być przyjazny dla użytkownika i umożliwiać swobodne korzystanie z aplikacji za pomocą dotyku.\nModel dystrybucji oprogramowania dla urządzeń mobilnych zazwyczaj opiera się na sklepach internetowych, takich jak App Store dla systemu iOS czy Google Play dla systemu Android. Dzięki temu użytkownicy mogą łatwo znaleźć i pobrać aplikacje, a deweloperzy mogą łatwo dystrybuować swoje oprogramowanie. Inne modele dystrybucji oprogramowania dla urządzeń mobilnych to na przykład dystrybucja bezpośrednio przez deweloperów lub przez firmowe sklepy aplikacji."),
        
        Fiszki(name: "Proces tworzenia aplikacji w Unity",
                  description: "Unity to platforma do tworzenia gier i aplikacji interaktywnych, która umożliwia tworzenie aplikacji zarówno dla komputerów, jak i urządzeń mobilnych. Oto ogólny proces tworzenia aplikacji w Unity:\nUtworzenie nowego projektu: na początek należy utworzyć nowy projekt w Unity i określić jego nazwę, lokalizację i ustawienia.\nModelowanie i tworzenie tekstur: następnie należy zająć się modelowaniem obiektów 3D oraz tworzeniem tekstur, które będą użyte w grze lub aplikacji. Można to zrobić za pomocą specjalistycznych narzędzi do modelowania 3D, takich jak Blender czy 3ds Max.\nImportowanie zasobów: po stworzeniu modeli i tekstur należy je zaimportować do Unity. W tym celu należy skorzystać z narzędzia Import w panelu Project.\nTworzenie sceny: następnie należy zająć się tworzeniem sceny gry lub aplikacji. W tym celu należy ustawić obiekty 3D na odpowiednich pozycjach oraz dodać światła i efekty specjalne.\nSkryptowanie: kolejnym krokiem jest dodanie funkcjonalności do aplikacji za pomocą skryptów napisanych w języku C# lub UnityScript. Skrypty pozwalają na zdefiniowanie zachowań obiektów w grze lub aplikacji oraz na obsługę zdarzeń i interakcji użytkownika.\nTestowanie i debugowanie"),
        
        Fiszki(name: "Typy danych, zmienne , funkcje .w Unity",
                  description: "Unity to platforma do tworzenia gier i aplikacji interaktywnych, która używa języka C# do skryptowania zachowań obiektów i obsługi zdarzeń. W Unity istnieje kilka podstawowych typów danych, takich jak:\nint (całkowita): służy do przechowywania liczb całkowitych, np. 1, 2, 3 itp.\nfloat (zmiennoprzecinkowa): służy do przechowywania liczb zmiennoprzecinkowych, np. 1.5, 2.3, 3.14 itp.\nbool (logiczna): służy do przechowywania wartości logicznych true (prawda) lub false (fałsz).\nstring (ciąg znaków): służy do przechowywania ciągów znaków, np. Hello World!.\nZmienne są to pojemniki do przechowywania danych w pamięci komputera. Aby utworzyć zmienną w Unity, należy określić jej typ, nazwę i przypisać jej wartość początkową.\nFunkcje to fragmenty kodu, które służą do wykonywania określonych zadań. Aby utworzyć funkcję w Unity, należy zdefiniować jej nazwę, typ zwracanej wartości (jeśli taka jest) oraz listę argumentów (jeśli taka jest)"),
        
        Fiszki(name: "Tworzenie klas i obiektów w c#",
                  description: "Klasy są to szablony do tworzenia obiektów, które zawierają informacje o tym, jakie dane i funkcje powinny być dostępne w obiekcie. Aby utworzyć klasę w C#, należy użyć słowa kluczowego class i zdefiniować nazwę klasy. Można również dodać pola (zmienne), które będą przechowywać dane oraz metody (funkcje), które będą wykonywać określone zadania. Przykład:\nclass Osoba { public string Imię; public string Nazwisko; public int Wiek; public stringPrzedstawSie() { return 'Cześć, nazywam się ' + Imię + ' ' + Nazwisko + ' i mam ' + Wiek + ' lat.'; } }\nObiekty są to konkretne egzemplarze klas, które zawierają konkretne dane i funkcje. Aby utworzyć obiekt w C#, należy utworzyć nowy egzemplarz klasy za pomocą operatora new i przypisać go do zmiennej. Następnie można użyć operatora ., aby uzyskać dostęp do pól i metod obiektu. Przykład:\nOsoba osoba1 = new Osoba(); osoba1.Imię = 'Anna'; osoba1.Nazwisko = 'Kowalska'; osoba1.Wiek = 25; string przedstawienie = osoba1.PrzedstawSie(); Debug.Log(przedstawienie); // wyświetli 'Cześć, nazywam się Anna Kowalska i mam 25 lat.'"),
        
        Fiszki(name: "Zasady projektowania aplikacji na terminale mobilne przy wykorzystaniu programowania sieciowego",
                  description: "Oto kilka zasad projektowania aplikacji na terminale mobilne przy wykorzystaniu programowania sieciowego:\nZoptymalizuj zużycie danych: Aplikacje mobilne często korzystają z połączenia sieciowego, więc ważne jest, aby minimalizować ilość danych przesyłanych i odbieranych przez aplikację. Można to osiągnąć przez optymalizację rozmiaru plików, kompresję danych i unikanie niepotrzebnych zapytań do serwera.\nUżywaj asynchronicznych metod do łączenia się z serwerem: Łączenie się z serwerem za pomocą synchronicznych metod może spowolnić aplikację lub spowodować jej zamrożenie. Dlatego warto używać asynchronicznych metod, które pozwalają aplikacji na wykonywanie innych zadań podczas oczekiwania na odpowiedź z serwera.\nZoptymalizuj wydajność aplikacji: Aplikacje mobilne mogą działać na urządzeniach o różnych mocach obliczeniowych, więc ważne jest, aby zoptymalizować wydajność aplikacji, aby działała ona płynnie na różnych urządzeniach. Można to osiągnąć przez optymalizację kodu, unikanie niepotrzebnych operacji i używanie wydajnych algorytmów.\nZabezpiecz dane: Przesyłanie danych przez sieć może być narażone na różne rodzaje ataków, dlatego ważne jest, aby zabezpieczyć dane przed nieautoryzowanym dostępem. Można to zrobić przez szyfrowanie danych przy użyciu bezpiecznych algorytmów lub przez używanie protokołów bezpieczeństwa, takich jak HTTPS."),
        
        Fiszki(name: "Proszę podać modele barw wykorzystywane w popularnych programach do tworzenia grafiki 3D i animacji.",
                  description: "W popularnych programach do tworzenia grafiki 3D i animacji wykorzystywane są następujące modele barw:\nRGB (Red, Green, Blue) - model barw oparty na trzech podstawowych barwach: czerwonym, zielonym i niebieskim. Każda z tych barw jest reprezentowana przez osobny kanał składowy (R, G, B), a ich mieszanie pozwala uzyskać dowolny kolor.\nCMYK (Cyan, Magenta, Yellow, Key) - model barw oparty na czterech podstawowych barwach: cyan (błękitny), magenta (pomarańczowy), żółty i key (czarny). Ten model jest szczególnie popularny w drukarce, ponieważ pozwala uzyskać bardzo dobrą jakość druku.\nHSL (Hue, Saturation, Lightness) - model barw oparty na trzech parametrach: odcieniu (hue), nasyceniu (saturation) i jasności (lightness). Ten model umożliwia łatwe zmiany odcienia, nasycenia i jasności koloru bez zmiany jego charakteru.\nLAB (Lightness, a, b) - model barw oparty na trzech parametrach: jasności (lightness), barwie a (odcieniu) i barwie b (nasyceniu). Ten model jest szczególnie przydatny do dokładnego reprezentowania kolorów widzialnego spektrum, ponieważ uwzględnia percepcję ludzkiego oka.\nXYZ (X, Y, Z) - model barw oparty na trzech parametrach: X, Y i Z. Ten model jest oparty na modelu RGB, ale uwzględnia również jasność i nasycenie kolorów. Jest często używany w systemach oświetleniowych i drukarskich."),
        
        Fiszki(name: "Na czym polega animacja poklatkowa, klatki kluczowe.",
                  description: "Animacja poklatkowa to technika tworzenia ruchomych obrazów, w której poszczególne klatki są tworzone ręcznie, jedna po drugiej. W procesie animacji poklatkowej twórca rysuje lub tworzy model 3D poszczególnych klatek animacji, a następnie 'łączy' je ze sobą, tworząc iluzję ruchu.\nKlatki kluczowe to poszczególne klatki animacji, które zawierają najważniejsze zmiany lub przejścia w animacji. Klatki kluczowe są używane w celu określenia pozycji, rotacji i skali obiektów w danej chwili czasu. Programy do tworzenia animacji pozwalają na tworzenie kluczowych klatek i automatyczne interpolowanie pozostałych klatek między nimi, co pozwala na łatwiejsze i szybsze tworzenie animacji."),
        
    ]}

